# Generated by Django 3.2.6 on 2021-08-10 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Tag')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField()),
                ('description', models.TextField(default='')),
                ('private', models.BooleanField(default=False)),
                ('maximum', models.IntegerField(default=100)),
                ('allowed', models.ManyToManyField(blank=True, related_name='private_rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Tag')),
                ('sent', models.DateTimeField(auto_now_add=True)),
                ('visible', models.BooleanField(default=True)),
                ('content', models.CharField(max_length=5000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.room')),
            ],
        ),
    ]
