# Generated by Django 3.2.7 on 2021-09-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('capital', models.CharField(max_length=100, verbose_name='Capital')),
                ('population', models.BigIntegerField(verbose_name='Population')),
                ('other_large_cities', models.CharField(max_length=1000, verbose_name='Other Large Cities')),
                ('national_language', models.CharField(max_length=1000, verbose_name='National Language')),
                ('national_animal', models.CharField(max_length=200, verbose_name='National Animal(s)')),
                ('national_sport', models.CharField(max_length=200, verbose_name='National Sport(s)')),
                ('currency', models.CharField(max_length=100, verbose_name='Currency')),
                ('key_landmarks', models.CharField(max_length=1000, verbose_name='Key Landmarks')),
                ('flag', models.ImageField(upload_to='flags/', verbose_name='Flag')),
                ('location', models.URLField(verbose_name='Location')),
                ('content', models.TextField(max_length=3000, verbose_name='Content')),
            ],
        ),
    ]
